# Generated by Django 5.1.3 on 2024-11-07 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='all_products',
            name='price',
            field=models.CharField(max_length=100),
        ),
    ]
